// <auto-generated />
namespace PMSWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Task_DataType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Task_DataType));
        
        string IMigrationMetadata.Id
        {
            get { return "202104071918329_Task_DataType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
